### ISSUE TITLE
Ability to generate _all.scss file if it doesn't already exist

### ISSUE THREAD

**Issue by pdehaan** [neagle/grunt-sass-directory-import#3]
It looks like if you specify a file `src` of "app/styles/modules/_all.scss" but the file doesn't already exist, nothing happens. It'd be nice if there was an option to generate the file if it doesn't exist.

```js
module.exports = function (grunt) {
  'use strict';

  grunt.config('sass_directory_import', {
    app: {
      options: {
        quiet: false
      },
      files: {
        src: [
          'app/styles/modules/_all.scss'
        ]
      }
    }
  });
};
```

It may be pretty nice if you could specify a src directory and dest file, something like this, where the generated `all.scss` would have a bunch of `@include 'modules/xyz';` lines:
```js
        src: [
          'app/styles/modules/**.scss'
        ],
        dest: 'app/styles/all.scss'
```

Or something like
```js
      files: {
        'app/styles/all.scss': ['app/styles/modules/**.scss']
      }
```

http://gruntjs.com/configuring-tasks#compact-format

**Comment by neagle** [comment]
Automatically generating the `_all.scss` file definitely makes sense: I'm a little surprised this doesn't do that already, but it's been a long time since I wrote this. I'll see if I can get to this tonight or sometime soon.

**Comment by neagle** [comment]
So I thought about this on the drive home, and I remembered why I set it up the way I did initially (sorry, it's been a while since I've used Grunt!): because the target `_all.scss` files can be anywhere (`/app/styles/**/_all.scss`) and the plugin simply iterates over them.

If you'd like to create a pull request that allows the plugin to be used in the way you described and also preserves the original use, I'd be happy to merge it in, but I don't think it's a feature that I want to take time to add at the moment.

**Comment by neagle** [comment]
Not that I love sending anyone away from my projects, but [grunt-sass-globbing](https://www.npmjs.com/package/grunt-sass-globbing) (which didn't exist when I made my plugin) looks like it does exactly what you want. :)
